from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import hashlib
import io
from datetime import datetime, timezone

async def generate_nabh_report(hospital_name: str, start_date: str, end_date: str, stats: dict, generated_by: str):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    # Header
    elements.append(Paragraph(f"<b>NABH Compliance Report</b>", styles['Title']))
    elements.append(Paragraph(f"Hospital: {hospital_name}", styles['Normal']))
    elements.append(Paragraph(f"Period: {start_date} to {end_date}", styles['Normal']))
    elements.append(Paragraph(
        f"Generated By: {generated_by} on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", 
        styles['Normal']
    ))
    elements.append(Spacer(1, 20))

    # Data table
    data = [
        ["COP", "Description", "Compliance", "Evidence"],
        ["7.3", "Post-discharge follow-up documented", f"{stats.get('follow_up_rate', 0)}%", f"{stats.get('follow_ups', 0)} patients"],
        ["7.3.1", "Follow-up within 24-48 hours", f"{stats.get('early_follow_up_rate', 0)}%", f"{stats.get('early_follow_ups', 0)} patients"],
        ["7.4", "Patient feedback tracking", f"{stats.get('feedback_rate', 0)}%", f"{stats.get('feedback_count', 0)} responses"],
        ["5.6", "Continuity of care documentation", "100%", "All patients enrolled in Ojas"],
    ]

    t = Table(data)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc')),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 30))

    # Build PDF first
    doc.build(elements)

    # Calculate hash AFTER build (when PDF is complete)
    buffer.seek(0)
    pdf_bytes = buffer.getvalue()
    report_hash = hashlib.sha256(pdf_bytes).hexdigest()[:16]

    # Return buffer and hash
    buffer.seek(0)
    return buffer, report_hash
